### ISSUE TITLE
Limitations of Testing

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#2237]
We're running into an issue where image downloads are taking too long that Travis is halting progress. I'm wondering what we could do to fix this. Could we potentially transition to GitHub actions? Are there any optimizations we could make to Glotter? Travis recommends making separate jobs: https://travis-ci.community/t/how-to-extend-the-maximum-time-limit-for-jobs-in-travis-ci/3874/2

**Comment by jrg94** [comment]
> $ python runner.py download
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated

**Comment by jrg94** [comment]
Actually, it looks like Travis has a tool exactly for this: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

**Comment by auroq** [comment]
If you're refering to https://travis-ci.com/github/TheRenegadeCoder/sample-programs/builds/190335361 I don't think it is a matter of taking too long per se especially since subsequent runs seem to pass.

If you read the error message it stalls when output is not received in a given amount of time indicating that the build stalled. We're not hitting a max timeout, we're getting stalled.

Additional context is that while downloading images, glotter does output while downloading. Unfortunately due to weirdness with CI pipelines, non-interactive login, etc... that output is only flushed and displayed after each image is full downloaded not during. (You should see different behavior locally).

Given all that context, I don't think there is any change we can make to make that more efficient besides using smaller images which we already try to do. That said this failure specifically and some previously seem to be other issues. I think that for whatever reason, things are really halting. Could be just the nature of running on limited hardware with a free CI system.

**Comment by auroq** [comment]
As far as optimizations, though, as I think they will be necessary soon. I'm looking into multi-threading downloads and test runs as well as adding logic to the container factory to decommission containers if we have too many running simultaneously.

**Comment by jrg94** [comment]
I'm getting two more pull requests that are halting as well. I've tried rerunning them a few times, but they keep stalling.

Everything you say makes sense! I'm wondering if we can dodge this issue entirely by switching CI tools or trying this travis wait script.

**Comment by auroq** [comment]
One more thought, the first limit I think we're likely to hit would be storage space with all of these images. We might want to add some image deletion to glotter. That could be what we're hitting now.

**Comment by auroq** [comment]
How about we try the wait first. Then we can debate CI tools. :weary:

**Comment by auroq** [comment]
Trying things out on local now as well.

**Comment by auroq** [comment]
My hard drive is quickly filling up with docker images, but I'm not noticing any output bugs locally. I will have to take a look at this later after I get off work. If I find something, I'll try to patch it and get a pull request out to you.

**Comment by jrg94** [comment]
No worries! I'm not sure what's happening either, but I'll keep poking around.

**Comment by jrg94** [comment]
Looks like adding the wait has mitigated the issue for the time being.

**Comment by jrg94** [comment]
I'm reopening this issue because it seems that Travis CI has added a fee: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

I can no longer run builds because we're out of "credits." Will be looking at alternatives this summer.
