### ISSUE TITLE
Incorporate Solutions from InEveryLang Repo

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#326]
Recently, I [reached out](https://github.com/josephwegner/ineverylang/issues/6) to [Joe Wegner](https://github.com/josephwegner), the owner of the inEveryLang repo, to see if we could incorporate some of their work into the collection. They agreed as long as we respect each contributor's work. I think that's totally fair! In fact, if there's no easy way to do it, I may reach out to the original contributors and ask if they'd like their work here.

**Comment by chrboe** [comment]
You're right, that might be an issue. I think the README approach is fine as well, since it documents the source in much the same way.

I'm a little confused by your syntax example though. Do you just mean that we should add an extra link for the source next to the original link? Also, are you referencing the top-level README, or do you want to individually document sources for each of the languages?
