### ISSUE TITLE
Pyret Docker Image Bug

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#3470]
I am toying with Pyret, but the docs are pretty rough. It seems that you can pass information on the command line by using the `cmdline` import. However, the current image throws up the help menu if any additional arguments are passed on the command line. 

For reference, [I was looking at this script](https://github.com/brownplt/pyret-lang/blob/horizon/examples/parse-and-print.arr) and noticed that it had an import for `cmdline`. I can't find any references to this package in the docs, but there are some references to it in the GitHub issues: https://github.com/brownplt/pyret-lang/issues?q=is%3Aissue+cmdline+is%3Aclosed. 

At any rate, there are not many solutions that can be written until this issue is resolved.

**Comment by rzuckerm** [comment]
@jrg94 It looks like there is a new version of pyret that was published last month -- 0.0.27. I just published a new docker image:
`0.0.27-2`

**Comment by rzuckerm** [comment]
brownplt/pyret-npm#4 logged

**Comment by rzuckerm** [comment]
PR brownplt/pyret-npm#5 created. I'll give it a month to get reviewed. If it does not, I'll release a new docker image with this change so that command-line arguments can be supported. BTW, see [this](https://github.com/rzuckerm/pyret-npm/blob/add-cmdline-args/ahoy-world-args.arr) for details on how to do command-line arguments in pyret.
