### ISSUE TITLE
Incorporate Style Guides in Repo

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#614]
I think it might be cool to include style guides alongside each language. That way when we have new contributions, we can evaluate them objectively. 

Im not sure where we would put these guides at the moment, but it may be nice to  add a naming conventions section to the READMEs. 

Of course, it may just be easier to link official style guides in the READMEs. 

Something to think about!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Noah11012** [comment]
Languages like C and C++ have different styles due to a lack of an official style guide. Languages like JS, Go, and Rust have a community accepted style that every formatter for those languages uses.

For Go and Rust, we can look at what the official style guide is for those languages. For C and C++ we might have to decided from several different style guides including LLVM, Mozilla, Google.

**Comment by jrg94** [comment]
This will be a bit more informal I think. Style guides should just be included in the reference links
